services:
    devcontainer:
        build:
            dockerfile: devcontainer.DockerFile
        restart: always
        command: sleep infinity
        volumes:
            - ../../:/workspaces:cached
