# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
    push:
    pull_request:
        branches: [main]
jobs:
    basic-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 23.x
              uses: actions/setup-node@v5
              with:
                  node-version: 23.x
                  cache: 'npm'
            - run: npm ci
            - run: ./node_modules/.bin/tsc --project ./tsconfig.app-check.json
            - run: ./node_modules/.bin/prettier . --check
            - run: ./node_modules/.bin/eslint "./**/*.ts"
    coverage:
        if: github.event.repository.visibility == 'public'
        needs: basic-checks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 23.x
              uses: actions/setup-node@v5
              with:
                  node-version: 23.x
                  cache: 'npm'
            - run: npm ci
            - name: Build
              run: ./node_modules/.bin/tsc --project ./tsconfig.app.json
            - name: Generate coverage
              run: ./node_modules/.bin/c8 --config=./.c8rc.coveralls.json node ./tests.ts
            - name: Coveralls GitHub Action
              uses: coverallsapp/github-action@v2.2.3
              with:
                  file: './coverage/lcov.info'
